title: Blog de Actividades de Aventura
author: Roman1010-es
email: jaunavoland@gmail.com
theme: jekyll-theme-minimal
description: > # this means to ignore newlines until "baseurl:"
  Blog de deportes de aventura. Actividades, ocio y entretenimiento en la naturaleza

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
